// Importing each node module registers it (side effect) into NODE_REGISTRY.
import './triggerNodes';
import './httpRequest';
import './ifNode';
import './filterNode';
import './splitOutNode';
import './aggregateNode';
import './sortNode';
import './limitNode';
import './removeDuplicatesNode';
import './itemListsNode';
import './compareDatasetsNode';
import './noOpNode';
import './dateTimeNode';
import './htmlExtractNode';
import './markdownHtmlNode';
import './xmlJsonNode';
import './cryptoNode';
import './compressionNode';
import './textParserNode';
import './stopAndErrorNode';
import './renameKeysNode';
import './moveBinaryDataNode';
import './simulateNode';
import './debugHelperNode';
import './setNode';
import './codeNode';
import './mergeNode';
import './slackNode';
import './openaiNode';
import './anthropicNode';
import './geminiNode';
import './localLlmNode';
import './groqNode';
import './mistralNode';
import './textClassifierNode';
import './sentimentAnalysisNode';
import './entityExtractorNode';
import './summarizerNode';
import './qaChainNode';
import './subConfigNodes';
import './structuredOutputParserNode';
import './autoFixingOutputParserNode';
import './ragNode';
import './browserAutomationNode';
import './switchNode';
import './waitNode';
import './forEachNode';
import './moreIntegrations';
import './businessIntegrations';
import './cloudIntegrations';
import './agentNode';
import './redisMemoryNode';
import './emailNode';
import './googleSheetsNode';
import './dataTableNode';
import './fileNode';
import './pmIntegrations';
import './productivityIntegrations';
import './devInfraIntegrations';
import './financeIntegrations';
import './marketingIntegrations';
import './schedulingIntegrations';
import './airtableNode';
import './socialIntegrations';

import { loadCommunityNodes } from './communityLoader';
loadCommunityNodes();

export { NODE_REGISTRY } from './types';
export type { NodePlugin, NodeExecutionContext, NodeExecutionResult } from './types';