import type { WorkflowGraph, WorkflowNode } from '@flowforge/shared-types';

function pyId(nodeId: string): string {
  return `t_${nodeId.replace(/[^a-zA-Z0-9]/g, '_')}`;
}

/** Emits a CrewAI script that models each FlowForge node as a Task run by a
 *  single general-purpose Agent, wired in the same topological order as the
 *  workflow graph. CrewAI's Process.sequential expects a linear task list,
 *  so branching (IF/Switch) nodes are flattened to their first outgoing
 *  edge with a comment noting the branch that was dropped — CrewAI doesn't
 *  have a native conditional-routing primitive to map onto. */
export function exportToCrewAI(graph: WorkflowGraph, workflowName: string): string {
  const order = topologicalOrder(graph);
  const lines: string[] = [];

  lines.push('"""');
  lines.push(`CrewAI export of FlowForge workflow: ${workflowName}`);
  lines.push('Generated by FlowForge. Branching nodes (if/switch) are flattened to their');
  lines.push('first outgoing path — CrewAI\'s sequential process has no native branch primitive.');
  lines.push('"""');
  lines.push('from crewai import Agent, Task, Crew, Process');
  lines.push('');
  lines.push('agent = Agent(');
  lines.push(`    role="${workflowName} executor",`);
  lines.push('    goal="Execute each step of the imported FlowForge workflow faithfully",');
  lines.push('    backstory="A general-purpose worker agent standing in for FlowForge\'s node executors.",');
  lines.push('    verbose=True,');
  lines.push(')');
  lines.push('');

  const byId = new Map(graph.nodes.map((n) => [n.id, n]));
  const taskVars: string[] = [];
  for (let i = 0; i < order.length; i++) {
    const node = byId.get(order[i])!;
    const varName = pyId(node.id);
    taskVars.push(varName);
    lines.push(`${varName} = Task(`);
    lines.push(`    description="${describeNode(node)}",`);
    lines.push(`    expected_output="Output of FlowForge node '${node.label ?? node.id}' (type=${node.type})",`);
    lines.push('    agent=agent,');
    if (i > 0) lines.push(`    context=[${taskVars[i - 1]}],`);
    lines.push(')');
    lines.push('');
  }

  lines.push('crew = Crew(');
  lines.push(`    agents=[agent],`);
  lines.push(`    tasks=[${taskVars.join(', ')}],`);
  lines.push('    process=Process.sequential,');
  lines.push('    verbose=True,');
  lines.push(')');
  lines.push('');
  lines.push('if __name__ == "__main__":');
  lines.push('    result = crew.kickoff()');
  lines.push('    print(result)');
  lines.push('');

  return lines.join('\n');
}

function describeNode(node: WorkflowNode): string {
  const paramsPreview = JSON.stringify(node.params).slice(0, 200).replace(/"/g, "'");
  return `Run FlowForge node '${node.label ?? node.id}' (type: ${node.type}) with params ${paramsPreview}`;
}

/** Kahn's algorithm; falls back to declaration order for nodes involved in a
 *  cycle (workflow graphs shouldn't have cycles, but exporters should never
 *  throw on malformed input). */
function topologicalOrder(graph: WorkflowGraph): string[] {
  const inDegree = new Map(graph.nodes.map((n) => [n.id, 0]));
  const adjacency = new Map<string, string[]>();
  for (const edge of graph.edges) {
    inDegree.set(edge.target, (inDegree.get(edge.target) ?? 0) + 1);
    if (!adjacency.has(edge.source)) adjacency.set(edge.source, []);
    adjacency.get(edge.source)!.push(edge.target);
  }

  const queue = graph.nodes.filter((n) => (inDegree.get(n.id) ?? 0) === 0).map((n) => n.id);
  const result: string[] = [];
  const seen = new Set<string>();

  while (queue.length) {
    const id = queue.shift()!;
    if (seen.has(id)) continue;
    seen.add(id);
    result.push(id);
    for (const next of adjacency.get(id) ?? []) {
      inDegree.set(next, (inDegree.get(next) ?? 0) - 1);
      if ((inDegree.get(next) ?? 0) <= 0) queue.push(next);
    }
  }

  for (const node of graph.nodes) {
    if (!seen.has(node.id)) result.push(node.id);
  }
  return result;
}
