import type { WorkflowGraph } from '@flowforge/shared-types';

function pyId(nodeId: string): string {
  return `n_${nodeId.replace(/[^a-zA-Z0-9]/g, '_')}`;
}

/** Emits a runnable LangGraph `StateGraph` Python script. Each FlowForge
 *  node becomes a graph node function stubbed with its params as a comment
 *  (LangGraph nodes are arbitrary Python callables, so we can't
 *  auto-translate node logic — but the graph topology, conditionals, and
 *  entry/exit points come across exactly). */
export function exportToLangGraph(graph: WorkflowGraph, workflowName: string): string {
  const lines: string[] = [];
  lines.push('"""');
  lines.push(`LangGraph export of FlowForge workflow: ${workflowName}`);
  lines.push('Generated by FlowForge — fill in each node function body with the real logic.');
  lines.push('"""');
  lines.push('from langgraph.graph import StateGraph, END');
  lines.push('from typing import TypedDict, Any');
  lines.push('');
  lines.push('class WorkflowState(TypedDict, total=False):');
  lines.push('    data: Any');
  lines.push('');

  for (const node of graph.nodes) {
    const fn = pyId(node.id);
    lines.push(`def ${fn}(state: WorkflowState) -> WorkflowState:`);
    lines.push(`    """FlowForge node: ${node.label ?? node.type} (type=${node.type})`);
    lines.push(`    params: ${JSON.stringify(node.params)}`);
    lines.push('    """');
    lines.push('    # TODO: port this node\'s logic');
    lines.push('    return state');
    lines.push('');
  }

  lines.push('graph = StateGraph(WorkflowState)');
  for (const node of graph.nodes) {
    lines.push(`graph.add_node("${node.id}", ${pyId(node.id)})`);
  }
  lines.push('');

  const hasIncoming = new Set(graph.edges.map((e) => e.target));
  const entryNodes = graph.nodes.filter((n) => !hasIncoming.has(n.id));
  for (const entry of entryNodes) {
    lines.push(`graph.set_entry_point("${entry.id}")`);
  }
  lines.push('');

  // Group edges by source to detect conditional (IF/Switch) fan-out.
  const bySource = new Map<string, typeof graph.edges>();
  for (const edge of graph.edges) {
    if (!bySource.has(edge.source)) bySource.set(edge.source, []);
    bySource.get(edge.source)!.push(edge);
  }
  for (const [source, outEdges] of bySource) {
    if (outEdges.length === 1 && !outEdges[0].sourceHandle) {
      lines.push(`graph.add_edge("${source}", "${outEdges[0].target}")`);
    } else {
      lines.push(`def ${pyId(source)}_router(state: WorkflowState) -> str:`);
      lines.push('    # TODO: replicate this node\'s branch condition');
      lines.push(`    return "${outEdges[0].target}"`);
      lines.push('');
      const mapping = outEdges.map((e) => `"${e.target}": "${e.target}"`).join(', ');
      lines.push(`graph.add_conditional_edges("${source}", ${pyId(source)}_router, {${mapping}})`);
    }
  }

  const hasOutgoing = new Set(graph.edges.map((e) => e.source));
  for (const node of graph.nodes) {
    if (!hasOutgoing.has(node.id)) lines.push(`graph.add_edge("${node.id}", END)`);
  }

  lines.push('');
  lines.push('app = graph.compile()');
  lines.push('');
  lines.push('if __name__ == "__main__":');
  lines.push('    result = app.invoke({"data": {}})');
  lines.push('    print(result)');
  lines.push('');

  return lines.join('\n');
}
