import type { WorkflowGraph } from '@flowforge/shared-types';

function pyId(nodeId: string): string {
  return `node_${nodeId.replace(/[^a-zA-Z0-9]/g, '_')}`;
}

/** Emits a dependency-free Python script that walks the workflow graph and
 *  calls one stub function per node in topological order, threading a
 *  shared `context` dict between them — a minimal, framework-agnostic
 *  export for teams that just want the control flow as plain code they can
 *  drop into any pipeline. */
export function exportToPython(graph: WorkflowGraph, workflowName: string): string {
  const lines: string[] = [];
  lines.push('#!/usr/bin/env python3');
  lines.push('"""');
  lines.push(`Plain-Python export of FlowForge workflow: ${workflowName}`);
  lines.push('Generated by FlowForge. Each function below is a stub for one workflow node —');
  lines.push('fill in the body with the equivalent of that node\'s FlowForge configuration.');
  lines.push('"""');
  lines.push('from __future__ import annotations');
  lines.push('from typing import Any, Dict');
  lines.push('');

  const byId = new Map(graph.nodes.map((n) => [n.id, n]));
  for (const node of graph.nodes) {
    lines.push(`def ${pyId(node.id)}(context: Dict[str, Any]) -> Dict[str, Any]:`);
    lines.push(`    """${node.label ?? node.type} (type=${node.type})"""`);
    lines.push(`    params = ${JSON.stringify(node.params, null, 4).replace(/^/gm, '    ').trim()}`);
    lines.push('    # TODO: implement this node\'s behavior');
    lines.push(`    context["${node.id}"] = {"status": "ok", "params": params}`);
    lines.push('    return context');
    lines.push('');
  }

  lines.push('def run() -> Dict[str, Any]:');
  lines.push('    context: Dict[str, Any] = {}');

  const bySource = new Map<string, typeof graph.edges>();
  for (const edge of graph.edges) {
    if (!bySource.has(edge.source)) bySource.set(edge.source, []);
    bySource.get(edge.source)!.push(edge);
  }
  const hasIncoming = new Set(graph.edges.map((e) => e.target));
  const entryNodes = graph.nodes.filter((n) => !hasIncoming.has(n.id));

  const visited = new Set<string>();
  function emitFrom(nodeId: string, indent: string) {
    if (visited.has(nodeId)) return;
    visited.add(nodeId);
    const node = byId.get(nodeId);
    if (!node) return;
    lines.push(`${indent}context = ${pyId(nodeId)}(context)`);
    const outEdges = bySource.get(nodeId) ?? [];
    if (node.type === 'if' && outEdges.length > 1) {
      const trueEdge = outEdges.find((e) => e.sourceHandle === 'true') ?? outEdges[0];
      const falseEdge = outEdges.find((e) => e.sourceHandle === 'false') ?? outEdges[1];
      lines.push(`${indent}if context["${nodeId}"].get("branch", True):`);
      if (trueEdge) emitFrom(trueEdge.target, indent + '    ');
      else lines.push(`${indent}    pass`);
      lines.push(`${indent}else:`);
      if (falseEdge) emitFrom(falseEdge.target, indent + '    ');
      else lines.push(`${indent}    pass`);
    } else {
      for (const edge of outEdges) emitFrom(edge.target, indent);
    }
  }

  for (const entry of entryNodes) emitFrom(entry.id, '    ');
  lines.push('    return context');
  lines.push('');
  lines.push('');
  lines.push('if __name__ == "__main__":');
  lines.push('    result = run()');
  lines.push('    print(result)');
  lines.push('');

  return lines.join('\n');
}
