import { writeFile } from 'fs/promises';
import path from 'path';
import type { NodeDefinition } from '@flowforge/node-sdk';

/** `flowforge-node docs <entry-file>` — imports the node definition(s) from
 *  an entry file and emits a markdown reference doc (fields, types,
 *  defaults, required-ness) next to it as `<name>.docs.md`. Keeps node docs
 *  from drifting out of sync with the actual field schema, since they're
 *  generated from it directly rather than hand-maintained. */
export async function runDocs(args: string[]) {
  const entry = args[0];
  if (!entry) throw new Error('Usage: flowforge-node docs <entry-file>');

  const resolved = path.resolve(process.cwd(), entry);
  const mod = await import(resolved);
  const nodes: NodeDefinition[] = collectNodeDefinitions(mod);
  if (nodes.length === 0) throw new Error(`No NodeDefinition export found in ${entry}`);

  for (const node of nodes) {
    const md = renderMarkdown(node);
    const outPath = path.join(path.dirname(resolved), `${slug(node.type)}.docs.md`);
    await writeFile(outPath, md);
    console.log(`Wrote ${outPath}`);
  }
}

function collectNodeDefinitions(mod: Record<string, unknown>): NodeDefinition[] {
  const candidates = [mod.default, ...Object.values(mod)];
  return candidates.filter((c): c is NodeDefinition => !!c && typeof c === 'object' && 'type' in c && 'execute' in c);
}

function renderMarkdown(node: NodeDefinition): string {
  const lines: string[] = [];
  lines.push(`# ${node.displayName}`);
  lines.push('');
  lines.push(node.description);
  lines.push('');
  lines.push(`- **Type:** \`${node.type}\``);
  lines.push(`- **Category:** ${node.category ?? 'Uncategorized'}`);
  lines.push(`- **Version:** ${node.version}`);
  lines.push('');
  lines.push('## Fields');
  lines.push('');
  lines.push('| Key | Label | Type | Required | Default | Description |');
  lines.push('|---|---|---|---|---|---|');
  for (const field of node.fields) {
    lines.push(
      `| \`${field.key}\` | ${field.label} | ${field.type}${
        field.type === 'options' ? ` (${field.options?.map((o) => o.value).join(', ')})` : ''
      } | ${field.required ? 'yes' : 'no'} | ${field.default !== undefined ? '`' + JSON.stringify(field.default) + '`' : '—'} | ${field.description ?? ''} |`
    );
  }
  lines.push('');
  lines.push('_Generated by `flowforge-node docs` — do not hand-edit; re-run the command instead._');
  lines.push('');
  return lines.join('\n');
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-');
}
